image: node:18-buster

cache:
  paths:
    - node_modules/
    - .yarn

before_script:
  - yarn config set cache-folder .yarn
  - yarn install --frozen-lockfile --prefer-offline

tests:
  stage: test
  script:
    - make test

typescript:
  stage: test
  script:
    - yarn run tsc --noEmit

lint:
  stage: test
  script:
    - yarn run lint

pages:
  stage: deploy
  before_script:
    - yarn config set cache-folder .yarn
    - yarn install --frozen-lockfile --prefer-offline
    - apt-get update -qq && apt-get install -y hugo python3 python3-toml python3-yaml
  script:
    - make -C website build  # Build landing page into website/public/.
    - make apply-latest-basename  # Overwrite settings so the Router works in deployment.
    - make build  # Build latest application into build/.
    - rm -rf public/  # Remove the folder with the same name.
    - mv website/public public  # Put the landing site in place.
    - mv build public/releases/latest  # Put the application in place.
  artifacts:
    paths:
      - public
  only:
    - main
